# Generated by Django 6.0.5 on 2026-05-18 13:58

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_bookmarks_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-deactivate after this datetime', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pinned announcements remain visible after the user dismisses them'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_roles',
            field=models.JSONField(default=list, help_text='Role names that see this announcement; empty = broadcast to everyone'),
        ),
        migrations.AlterField(
            model_name='dashboardbookmark',
            name='emoji',
            field=models.CharField(default='📌', help_text='Emoji identifier for quick recognition', max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboardbookmark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='device_type',
            field=models.CharField(blank=True, help_text='mobile / tablet / pc', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System roles cannot be deleted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hrforce_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Corresponding user_id in HRForce — used for sync identification', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='notif_alert_triggered',
            field=models.BooleanField(default=True, help_text='Notify when a threshold alert fires'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='notif_etl_status',
            field=models.BooleanField(default=False, help_text='Notify on ETL pipeline completion'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='pinned_dashboards',
            field=models.JSONField(default=list, help_text='Ordered list of pinned dashboard keys'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='saved_filters',
            field=models.JSONField(default=dict, help_text='Persisted filter state per dashboard, keyed by dashboard name'),
        ),
    ]
