# Generated by Django 6.0.5 on 2026-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_hrforce_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hrforce_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Corresponding user id in HRForce — used for sync identification', null=True, unique=True),
        ),
    ]
