-- fact_transport_demand: One row per transport demand event
-- Grain: one demand = one pickup request from one client
-- Columns: demand_sk (PK), date_id (FK dim_date), client_sk (FK dim_client),
--          origin_site_sk (FK dim_site), destination_site_sk (FK dim_site),
--          vehicle_sk (FK dim_vehicle),
--          demand_id (business key), status (accepted/rejected/pending),
--          parcel_count, total_weight_kg, declared_value_dzd,
--          transport_cost_dzd, revenue_dzd, profit_dzd, margin_pct,
--          created_at, accepted_at, picked_up_at
-- TODO: Add partitioning by year_month for query performance
